### ISSUE TITLE
So confused about the return value of the get_loss_img2text_image function in the Trainer file.

### ISSUE THREAD

**Issue by CCaoWWei** [suoych/KEDs#1]
Thank you for open-sourcing the code. This article has been very insightful and inspiring to me. However, I have some questions while reviewing the code.

Q1：This function currently appears to only have the Lc loss from the paper and does not include the loss from the Lr component.

Q2：In the get_loss_img2text function, the loss and extra_loss within the if branch do not correspond to those in the else branch.

Q1：
![9PB}AMEUHPFA4 B(5RNQF98](https://github.com/suoych/KEDs/assets/66764181/840fca37-0c8a-41c3-bf10-4d03f35deb36)

Q2：
![@FK@NYAQ(CN@62O8$QZ~IAY](https://github.com/suoych/KEDs/assets/66764181/86a5dcd0-333d-40d4-8934-28f33ad3a558)

**Comment by suoych** [comment]
> Thank you for open-sourcing the code. This article has been very insightful and inspiring to me. However, I have some questions while reviewing the code.
> 
> Q1：This function currently appears to only have the Lc loss from the paper and does not include the loss from the Lr component.
> 
> Q2：In the get_loss_img2text function, the loss and extra_loss within the if branch do not correspond to those in the else branch.
> 
> Q1： ![9PB}AMEUHPFA4 B(5RNQF98](https://private-user-images.githubusercontent.com/66764181/345412047-840fca37-0c8a-41c3-bf10-4d03f35deb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDk0MDMsIm5iZiI6MTcyMDAwOTEwMywicGF0aCI6Ii82Njc2NDE4MS8zNDU0MTIwNDctODQwZmNhMzctMGM4YS00MWMzLWJmMTAtNGQwM2YzNWRlYjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzc2Zjc2MmMxYTllZmYwZmM0Mjg1NzljZmUwZGY5M2VlMDc3NmE0OTBjOTkxNWQ4YzU1NDdkMmMxNDE0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JYiVvaQG-8V1uQvS0PVySSduSQ_36PFOackB9Bvi388)
> 
> Q2： ![@FK@NYAQ(CN@62O8$QZ~IAY](https://private-user-images.githubusercontent.com/66764181/345413845-86a5dcd0-333d-40d4-8934-28f33ad3a558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDk0MDMsIm5iZiI6MTcyMDAwOTEwMywicGF0aCI6Ii82Njc2NDE4MS8zNDU0MTM4NDUtODZhNWRjZDAtMzMzZC00MGQ0LTg5MzQtMjhmMzNhZDNhNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNjNkNzcyODU4YjQ1YTgwOTRjY2U2OTE3NTUyMzljMzY0N2ViMzFmYWQ2N2NhMjNlYTFhNmQ5MGZlMDYzNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5EP-mYlVuaiUfwGY9_48Wzu_6UW6n-TzuOv_8L9AWl0)

Hi, Thank you for your interest!

First, I apologize for the raw code presented in the repo, promise I will reformat and add more docstrings.

For the first question, in our real implementation, we seperately train the two branches (Each with 4 GPUs). The get_loss_img2text_image function is the image-only contrastive branch and the get_loss_img2text is the textual alignment branch.

As for the second question, we only train the model using 4 cards thus you can always refer to the if branch. The else branch is only used for debug which can be ignored.

**Comment by CCaoWWei** [comment]
I understand now. Thank you for your response. ^_^

**Comment by CCaoWWei** [comment]
> > Thank you for open-sourcing the code. This article has been very insightful and inspiring to me. However, I have some questions while reviewing the code.
> > Q1：This function currently appears to only have the Lc loss from the paper and does not include the loss from the Lr component.
> > Q2：In the get_loss_img2text function, the loss and extra_loss within the if branch do not correspond to those in the else branch.
> > Q1： ![9PB}AMEUHPFA4 B(5RNQF98](https://private-user-images.githubusercontent.com/66764181/345412047-840fca37-0c8a-41c3-bf10-4d03f35deb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDk0MDMsIm5iZiI6MTcyMDAwOTEwMywicGF0aCI6Ii82Njc2NDE4MS8zNDU0MTIwNDctODQwZmNhMzctMGM4YS00MWMzLWJmMTAtNGQwM2YzNWRlYjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzc2Zjc2MmMxYTllZmYwZmM0Mjg1NzljZmUwZGY5M2VlMDc3NmE0OTBjOTkxNWQ4YzU1NDdkMmMxNDE0YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JYiVvaQG-8V1uQvS0PVySSduSQ_36PFOackB9Bvi388)
> > Q2： ![@FK@NYAQ(CN@62O8$QZ~IAY](https://private-user-images.githubusercontent.com/66764181/345413845-86a5dcd0-333d-40d4-8934-28f33ad3a558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDk0MDMsIm5iZiI6MTcyMDAwOTEwMywicGF0aCI6Ii82Njc2NDE4MS8zNDU0MTM4NDUtODZhNWRjZDAtMzMzZC00MGQ0LTg5MzQtMjhmMzNhZDNhNTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNjNkNzcyODU4YjQ1YTgwOTRjY2U2OTE3NTUyMzljMzY0N2ViMzFmYWQ2N2NhMjNlYTFhNmQ5MGZlMDYzNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5EP-mYlVuaiUfwGY9_48Wzu_6UW6n-TzuOv_8L9AWl0)
> 
> Hi, Thank you for your interest!
> 
> First, I apologize for the raw code presented in the repo, promise I will reformat and add more docstrings.
> 
> For the first question, in our real implementation, we seperately train the two branches (Each with 4 GPUs). The get_loss_img2text_image function is the image-only contrastive branch and the get_loss_img2text is the textual alignment branch.
> 
> As for the second question, we only train the model using 4 cards thus you can always refer to the if branch. The else branch is only used for debug which can be ignored.

I understand now. Thank you for your response. ^_^
