### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by znchen666** [suoych/KEDs#6]
Thanks for your great work! Could you please provide the "cc_subject.json" and "cc_other.json" for training? Or what is "cc3m_have_good.pkl" and "cc3m_have.pkl"?

**Comment by suoych** [comment]
Hi, cc_subject.json and cc_other.json are extracted by this file [https://github.com/suoych/KEDs/blob/main/extract_cc_noun.py](url). cc3m_have_good.pkl and cc3m_have.pkl are actually the captions in the cc3m dataset, which you can download following the guidelines provided by the dataset authors.

**Comment by znchen666** [comment]
Thank you very much!
